name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path -Path "requirements.txt") { pip install -r requirements.txt }
      
      - name: Download and extract cache
        shell: pwsh
        run: |
          # 下载7zip
          curl -L -o 7zr.exe https://www.7-zip.org/a/7zr.exe
          
          # 下载cache.7z
          curl -L -o cache.7z https://github.com/AbitCd/vndb-galgame-grouper/releases/download/v0.1/cache.7z
          
          # 创建目录并解压
          New-Item -ItemType Directory -Force -Path "fuzz/cache"
          .\7zr.exe x cache.7z -o"fuzz/cache" -y
      
      - name: Clean build directories
        run: |
          if (Test-Path -Path "build") { Remove-Item -Recurse -Force build }
          if (Test-Path -Path "dist") { Remove-Item -Recurse -Force dist }

      - name: Build with PyInstaller
        run: |
          pyinstaller main.spec

      - name: Copy cache files
        run: |
          mkdir -p dist/vndb-galgame-grouper/fuzz
          Copy-Item -Path "fuzz/cache" -Destination "dist/vndb-galgame-grouper/fuzz" -Recurse

      - name: Create ZIP archive
        run: |
          cd dist
          powershell Compress-Archive -Path vndb-galgame-grouper -DestinationPath vndb-galgame-grouper-windows.zip
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/vndb-galgame-grouper-windows.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}